// ─── Estilos ──────────────────────────────────────────────────────────────────
export const CLOSE_BTN_STYLE = { flexShrink: 0, background: 'var(--bg-elevated)', border: '2px solid var(--border)', borderRadius: '50%', width: 44, height: 44, fontSize: 'var(--admin-fs-xl)', fontWeight: 800, cursor: 'pointer', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', lineHeight: 1 };
export const ACCENT  = 'var(--accent)';
export const BG      = 'var(--bg-base)';
export const SURFACE = 'var(--bg-surface)';
export const BORDER  = 'var(--border)';
export const TEXT    = 'var(--text-primary)';
export const MUTED   = 'var(--text-secondary)';

export const s = {
  root:    { display: 'flex', height: '100vh', overflow: 'hidden', background: BG, color: TEXT, fontFamily: "'DM Sans', 'Inter', sans-serif" },
  sidebar: { background: SURFACE, borderRight: `1px solid ${BORDER}`, display: 'flex', flexDirection: 'column', padding: '24px 16px', height: '100%', flexShrink: 0, transition: 'width var(--transition-base) ease' },
  sidebarCollapsed: { width: 68 },
  sidebarExpanded: { width: 224 },
  nav:     { display: 'flex', flexDirection: 'column', gap: 4, flex: 1 },
  navItem: { display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px', borderRadius: 8, background: 'none', border: 'none', cursor: 'pointer', color: MUTED, fontSize: 'var(--admin-fs-md)', fontWeight: 500, textAlign: 'left', transition: 'background var(--transition-fast) ease, color var(--transition-fast) ease', minHeight: 44, minWidth: 44 },
  navActive:    { background: `${ACCENT}18`, color: ACCENT },
  navBadge:     { marginLeft: 'auto', background: 'var(--error)', color: '#ffffff', borderRadius: 10, padding: '1px 7px', fontSize: 'var(--admin-fs-xs)', fontWeight: 700 },
  sidebarToggle:{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 12, background: 'none', border: 'none', color: MUTED, cursor: 'pointer', fontSize: 'var(--admin-fs-lg)', minHeight: 44, minWidth: 44, borderRadius: 8, transition: 'background var(--transition-fast) ease, color var(--transition-fast) ease', marginTop: 'auto' },
  navItemCollapsed: { justifyContent: 'center', padding: '10px 0' },
  navLabelHidden: { display: 'none' },
  badgeHidden: { display: 'none' },

  main:       { flex: 1, padding: '32px 40px', overflowY: 'auto', height: '100%' },
  header:     { marginBottom: 28 },
  headerTitle:{ fontSize: 'var(--admin-fs-2xl)', fontWeight: 700, margin: 0, letterSpacing: '-0.5px', textWrap: 'balance' },
  headerSub:  { color: MUTED, fontSize: 'var(--admin-fs-md)', margin: '4px 0 0' },

  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16 },
  statCard:  { background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 12, padding: '18px 20px', boxShadow: '0 1px 3px rgba(0,0,0,0.04)', transition: 'box-shadow var(--transition-base) ease, transform var(--transition-base) ease', cursor: 'default' },
  statIcon:  { width: 36, height: 36, borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 'var(--admin-fs-lg)', marginBottom: 12 },
  statValue: { fontSize: 'var(--admin-fs-2xl)', fontWeight: 800, letterSpacing: '-0.5px', color: TEXT, lineHeight: 1.1, marginBottom: 4 },
  statLabel: { fontSize: 'var(--admin-fs-sm)', color: MUTED, fontWeight: 500, letterSpacing: '0.3px', textWrap: 'balance' },

  kpiSection:     { marginBottom: 32 },
  kpiSectionLabel:{ fontSize: 'var(--admin-fs-sm)', fontWeight: 600, color: MUTED, textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: 12, paddingLeft: 2, textWrap: 'balance' },
  kpiAlertCard:   { background: 'var(--warning-soft)', border: '1px solid var(--warning)', borderRadius: 12, padding: '18px 20px', display: 'flex', alignItems: 'center', gap: 14, boxShadow: '0 1px 3px rgba(0,0,0,0.04)', transition: 'box-shadow var(--transition-base) ease' },
  kpiAlertIcon:   { fontSize: 20, width: 40, height: 40, borderRadius: 10, background: 'var(--warning)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  kpiAlertValue:  { fontSize: 'var(--admin-fs-2xl)', fontWeight: 800, letterSpacing: '-0.5px', color: 'var(--warning)', lineHeight: 1.1 },
  kpiAlertLabel:  { fontSize: 'var(--admin-fs-sm)', fontWeight: 600, color: 'var(--warning)', letterSpacing: '0.3px' },
  kpiLoadingSkeleton: { background: 'var(--bg-elevated)', borderRadius: 12, animation: 'pulse 1.5s ease-in-out infinite' },

  section:     { marginTop: 32 },
  sectionHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sectionTitle:{ fontSize: 'var(--admin-fs-lg)', fontWeight: 600, textWrap: 'balance' },
  linkBtn:     { background: 'none', border: 'none', color: ACCENT, cursor: 'pointer', fontSize: 'var(--admin-fs-base)', fontWeight: 600, minHeight: 44, minWidth: 44, transition: 'color var(--transition-fast) ease' },

  filterRow: { display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' },
  filterBtn:  { background: 'none', border: `1px solid ${BORDER}`, color: MUTED, borderRadius: 7, padding: '6px 14px', fontSize: 'var(--admin-fs-base)', cursor: 'pointer', minHeight: 44, minWidth: 44, transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },
  filterBtnActive: { background: `${ACCENT}18`, borderColor: ACCENT, color: ACCENT, transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },

  table:     { background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 12, overflow: 'hidden' },
  tableHead: { display: 'grid', gridTemplateColumns: '2fr 1fr 0.5fr 0.8fr 1fr', padding: '12px 20px', borderBottom: `1px solid ${BORDER}`, background: 'var(--bg-elevated)' },
  th:        { fontSize: 'var(--admin-fs-sm)', color: MUTED, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.5px' },
  tableRow:  { display: 'grid', gridTemplateColumns: '2fr 1fr 0.5fr 0.8fr 1fr', padding: '14px 20px', alignItems: 'center', borderBottom: `1px solid ${BORDER}` },
  tableRowHover: { background: 'var(--bg-elevated)', cursor: 'pointer', transition: 'background var(--transition-fast) ease' },
  focusVisible: { outline: '2px solid var(--accent)', outlineOffset: '2px' },
  td:        { display: 'flex', alignItems: 'center', gap: 10 },
  tdNum:     { fontSize: 'var(--admin-fs-md)', fontWeight: 600, color: ACCENT },
  rowAvatar: { width: 32, height: 32, borderRadius: '50%', background: 'var(--bg-elevated)', color: MUTED, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 'var(--admin-fs-base)', fontWeight: 700, flexShrink: 0 },
  rowName:   { fontSize: 'var(--admin-fs-md)', fontWeight: 500 },
  rowEmail:  { fontSize: 'var(--admin-fs-sm)', color: MUTED },
  roleSelect:{ background: 'var(--bg-elevated)', border: `1px solid ${BORDER}`, color: TEXT, borderRadius: 6, padding: '5px 8px', fontSize: 'var(--admin-fs-sm)', cursor: 'pointer', width: '100%', maxWidth: '100%', boxSizing: 'border-box' },
  badge:     { fontSize: 'var(--admin-fs-sm)', fontWeight: 600, borderRadius: 6, padding: '3px 10px', textTransform: 'capitalize' },
  actionBtn: { background: 'none', border: `1px solid ${BORDER}`, color: MUTED, borderRadius: 6, padding: '5px 12px', fontSize: 'var(--admin-fs-base)', cursor: 'pointer', minHeight: 44, minWidth: 44, transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },
  actionBtnDanger: { borderColor: 'var(--error)', color: 'var(--error)', transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },

  reportCard:    { background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 12, padding: '18px 20px' },
  reportTop:     { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 },
  severityBadge: { fontSize: 'var(--admin-fs-xs)', fontWeight: 700, borderRadius: 4, padding: '3px 8px', letterSpacing: '0.5px' },
  statusPill:    { fontSize: 'var(--admin-fs-xs)', padding: '3px 8px', borderRadius: 999, background: 'var(--bg-elevated)', color: MUTED, fontWeight: 700 },

  summaryGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 12, marginBottom: 16 },
  summaryCard: { background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 10, padding: '12px 14px' },
  summaryTitle: { margin: '0 0 8px', fontSize: 'var(--admin-fs-md)' },
  summaryRow: { display: 'flex', justifyContent: 'space-between', fontSize: 'var(--admin-fs-base)', color: MUTED, marginBottom: 6 },
  summaryEmpty: { margin: 0, color: MUTED, fontSize: 'var(--admin-fs-base)' },
  reportFiltersGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 10, marginBottom: 18 },
  filterLabelWrap: { display: 'flex', flexDirection: 'column', gap: 6 },
  filterLabel: { fontSize: 'var(--admin-fs-sm)', color: MUTED, fontWeight: 600 },
  filterSelect: { background: 'var(--bg-elevated)', border: `1px solid ${BORDER}`, color: TEXT, borderRadius: 7, padding: '8px 10px', fontSize: 'var(--admin-fs-base)' },

  modalOverlay: { position: 'fixed', inset: 0, background: 'var(--overlay)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1200, padding: 16 },
  descriptionBox: { margin: 0, fontSize: 'var(--admin-fs-md)', color: TEXT, lineHeight: 1.5, background: 'var(--bg-surface)', padding: '10px 14px', borderRadius: 8, border: `1px solid ${BORDER}` },
  modalCard: { width: 720, maxWidth: '95vw', maxHeight: '90vh', overflowY: 'auto', background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 12, padding: 20 },
  detailGrid: { display: 'grid', gap: 10, marginBottom: 14 },
  detailRow: { display: 'grid', gridTemplateColumns: '150px 1fr', gap: 10, fontSize: 'var(--admin-fs-base)' },
  detailLabel: { color: MUTED },
  modalTextarea: { width: '100%', background: 'var(--bg-elevated)', border: `1px solid ${BORDER}`, color: TEXT, borderRadius: 8, padding: 10, fontSize: 'var(--admin-fs-base)', resize: 'vertical' },


  btnDelete:  { background: 'var(--error-soft)', border: '1px solid var(--error)', color: 'var(--error)', borderRadius: 7, padding: '7px 14px', fontSize: 'var(--admin-fs-base)', cursor: 'pointer', fontWeight: 500, transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },
  btnBan:     { background: 'var(--warning-soft)', border: '1px solid var(--warning)', color: 'var(--warning)', borderRadius: 7, padding: '7px 14px', fontSize: 'var(--admin-fs-base)', cursor: 'pointer', fontWeight: 500, transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },
  btnDismiss: { background: 'none', border: `1px solid ${BORDER}`, color: MUTED, borderRadius: 7, padding: '7px 14px', fontSize: 'var(--admin-fs-base)', cursor: 'pointer', minHeight: 44, minWidth: 44, transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },

  // Dealer applications
  dealerEmpty: { color: MUTED, fontSize: 'var(--admin-fs-md)', padding: '24px 0' },
  dealerSectionTitle: { fontSize: 'var(--admin-fs-md)', fontWeight: 600, color: MUTED, marginBottom: 12 },
  dealerError: { color: 'var(--error)', fontSize: 'var(--admin-fs-base)', textAlign: 'center', margin: '8px 0' },
  dealerList: { display: 'flex', flexDirection: 'column', gap: '16px' },
  dealerSubList: { display: 'flex', flexDirection: 'column', gap: '10px' },
  dealerRow: { padding: '16px', border: `1px solid ${BORDER}`, borderRadius: 'var(--radius-lg)', background: SURFACE, display: 'flex', flexDirection: 'column', gap: '8px' },
  dealerRowHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '12px', flexWrap: 'wrap' },
  dealerName: { margin: 0, fontWeight: 600, fontSize: 'var(--admin-fs-md)', color: TEXT },
  dealerPhone: { margin: '2px 0 0', fontSize: 'var(--admin-fs-base)', color: MUTED },
  dealerMotivation: { margin: 0, fontSize: 'var(--admin-fs-base)', color: MUTED, fontStyle: 'italic' },
  dealerDate: { margin: 0, fontSize: 'var(--admin-fs-sm)', color: 'var(--text-muted, var(--text-secondary))' },
  dealerActions: { display: 'flex', gap: '8px', marginTop: '4px' },
  dealerRejectionReason: { margin: 0, fontSize: 'var(--admin-fs-sm)', color: 'var(--error)' },
  dealerBadge: { padding: '3px 10px', borderRadius: '999px', fontSize: 'var(--admin-fs-sm)', fontWeight: 600 },
  dealerBadgePending: { background: 'var(--warning-soft)', color: 'var(--warning)', border: '1px solid var(--warning)' },
  dealerBadgeApproved: { background: 'var(--success)18', color: 'var(--success)', border: '1px solid var(--success)' },
  dealerBadgeRejected: { background: 'var(--error-soft)', color: 'var(--error)', border: '1px solid var(--error)' },
  dealerBtnApprove: { padding: '7px 16px', borderRadius: 'var(--radius-md)', border: 'none', background: 'var(--success)', color: '#fff', fontSize: 'var(--admin-fs-base)', fontWeight: 600, transition: 'opacity var(--transition-fast) ease' },
  dealerBtnReject: { padding: '7px 16px', borderRadius: 'var(--radius-md)', border: '1px solid var(--error)', background: 'transparent', color: 'var(--error)', fontSize: 'var(--admin-fs-base)', fontWeight: 600, cursor: 'pointer', transition: 'background var(--transition-fast) ease, border-color var(--transition-fast) ease, color var(--transition-fast) ease' },
  dealerModalOverlay: { position: 'fixed', inset: 0, background: 'var(--overlay)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, padding: 16 },
  dealerModalCard: { background: SURFACE, borderRadius: 'var(--radius-xl)', padding: '24px', width: '100%', maxWidth: '400px', display: 'flex', flexDirection: 'column', gap: '14px' },
  dealerModalTitle: { margin: 0, fontSize: 'var(--admin-fs-lg)', fontWeight: 600, color: TEXT },
  dealerModalLabel: { fontSize: 'var(--admin-fs-base)', fontWeight: 500, color: TEXT, display: 'block', marginBottom: 6 },
  dealerModalInput: { width: '100%', boxSizing: 'border-box', padding: '9px 12px', borderRadius: 'var(--radius-md)', border: `1px solid ${BORDER}`, background: 'var(--bg-elevated)', color: TEXT, fontSize: 'var(--admin-fs-md)', minHeight: '72px', resize: 'vertical', fontFamily: 'inherit' },
  dealerModalBtnRow: { display: 'flex', gap: '8px' },
  dealerModalConfirm: { flex: 1, padding: 10, borderRadius: 'var(--radius-md)', border: 'none', background: 'var(--error)', color: '#fff', fontWeight: 600, cursor: 'pointer' },
  dealerModalCancel: { flex: 1, padding: 10, borderRadius: 'var(--radius-md)', border: `1px solid ${BORDER}`, background: 'transparent', color: TEXT, cursor: 'pointer' },

  configCard: { background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: 12, overflow: 'hidden' },
  configRow:  { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '14px 20px', borderBottom: `1px solid ${BORDER}` },
  configParam:{ fontSize: 'var(--admin-fs-md)', fontWeight: 500, color: TEXT },
  configNote: { fontSize: 'var(--admin-fs-sm)', color: MUTED, marginTop: 2 },
  configValue:{ fontSize: 'var(--admin-fs-xl)', fontWeight: 800, letterSpacing: '-0.5px' },
};
